---
title: Predecir con regresión lineal simple
linktitle: 7.1 Regresión lineal simple
toc: true
type: docs
date: "2020-08-05T00:00:00+01:00"
draft: false
diagram: true
menu:
  example:
    parent: 7. Modelamiento
    weight: 1

# Prev/next pager order (if `docs_section_pager` enabled in `params.toml`)
weight: 3
---

## Tutorial

Te sugiero revisar el siguiente tutorial para el cálculo de un modelo de regresión simple en {{< icon name="r-project" pack="fab" >}}:

<iframe width="560" height="315" src="https://www.youtube.com/embed/-p02G7NXlSk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Solicitamos nuestra base de datos desde la nube

    library(rio)
    base_trabajadores="https://github.com/DataPolitica/salidas/raw/master/Data/trabajadores.sav"
    trabajadores=import(base_trabajadores)
    attach(trabajadores)

    names(trabajadores)

    ##  [1] "id"              "sexo"            "fechnac"         "educ"           
    ##  [5] "catlab"          "salario_actual"  "salario_inicial" "antiguedad"     
    ##  [9] "experiencia"     "minoría"         "directivo"

## Solicitamos un diagrama de dispersión

En este caso vamos a seleccionar las dos variables (el salario inicial y salario final) y solicitar un diagrama de dispersión. 

    plot(salario_actual~salario_inicial)
![Image](/cursos/7-1-1.jpg)

Como vemos en el diagrama, podemos ver una línea fácilmente. Ello es un buen indicio de que ambas variables están correlacionadas linealmente; sin embargo, es necesario realizar el test estadístico de correlación para poder tener una mirada más fina. 

## Solicitamos el test de correlación

Para realizar el test de correlación necesitamos utilizar la función `cor.test`. Colocamos las variables de interés entre el paréntesis separado por una coma y lo solitiamos. 

    cor.test(salario_actual,salario_inicial)

    ## 
    ##  Pearson's product-moment correlation
    ## 
    ## data:  salario_actual and salario_inicial
    ## t = 40.276, df = 472, p-value < 2.2e-16
    ## alternative hypothesis: true correlation is not equal to 0
    ## 95 percent confidence interval:
    ##  0.8580696 0.8989267
    ## sample estimates:
    ##       cor 
    ## 0.8801175

{{% alert note %}}
En este caso hemos solicitado el R de Pearson como el test de correlación. Sin embargo, si la variable no posee una distribución normal sería más adecuado aplicar el Test de Spearman (método no paramétrico).
{{% /alert %}}

## Solicitamos el modelo de regresión simple

Para calcular un modelo de regresión debemos utilizar la función `lm()`. Dentro de los paréntesis colocamos las variables de la siguiente manera: variable_dependiente ~ variable_independiente. Al modelo le vamos a llamar *modelo1*:

    modelo1=lm(salario_actual~salario_inicial,data=trabajadores)

Luego de ello, podemos darnos cuenta que en nuestra sección de objetos (cuadrante superior derecho) ya figura el modelo1. Para solicitar los resultados colocamos la función `summary(modelo1)`

    summary(modelo1)

    ## 
    ## Call:
    ## lm(formula = salario_actual ~ salario_inicial, data = trabajadores)
    ## 
    ## Residuals:
    ##    Min     1Q Median     3Q    Max 
    ## -35424  -4031  -1154   2584  49293 
    ## 
    ## Coefficients:
    ##                  Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)     1.928e+03  8.887e+02    2.17   0.0305 *  
    ## salario_inicial 1.909e+00  4.741e-02   40.28   <2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 8115 on 472 degrees of freedom
    ## Multiple R-squared:  0.7746, Adjusted R-squared:  0.7741 
    ## F-statistic:  1622 on 1 and 472 DF,  p-value: < 2.2e-16

Luego de ello seguimos los pasos de nuestro flujograma:

![Image](/cursos/7-1-2.jpg)

## Paso 1: Comprobar si nuestro modelo es válido

Para ello, necesitamos ver la tabla ANOVA, vale decir, las últimas líneas de nuestro output del *modelo1*. 

Recordemos que estamos realizando una prueba de hipótesis, en la cual nuestras hipótesis son las siguientes:

| Hipótesis nula (H0)  | Hipótesis alterna (Ha) |
| ------------- | ------------- |
| El modelo no es válido  | El modelo es válido  |

Entonces leemos el p-valor. Como en este caso obtuvimos un p valor de <2.2e-16 entonces podemos ver que es menor a 0.05 (alpha), rechazamos la hipótesis nula y concluimos que **nuestro modelo es válido**.

## Paso 2: Capacidad explicativa del modelo

Para ello, debemos ver el valor del R2 ajustado. En este caso lo interpretamos de la siguiente manera:

![Image](/cursos/7-1-3.jpg)

En este caso, al tener un R2 ajustado de 0.7741 podemos concluir que nuestro modelo explica el 77.41% de la variabilidad de la dependiente (en este caso, salario actual)

## Paso 3: Verificar si la variable X aporta al modelo

El siguiente paso, luego de ver si nuestro modelo es válido y su capacidad explicativa, debemos ver si efectivamente nuestra variable explicativa aporta al modelo. Para ello, debemos visualizar nuestra tabla de coeficientes y analizar la línea que corresponde a la variable de nuestro interés. 

| Hipótesis nula (H0)  | Hipótesis alterna (Ha) |
| ------------- | ------------- |
| La variable X no aporta al modelo  | La variable X aporta al modelo  |

En este caso, el pvalor de *salario_inicial* nos salió <2e-16 ***. Por ello, al ser menor que 0.05, rechazamos nuestra hipótesis nula (la variable no aporta al modelo) y concluimos que efectívamente sí aporta al modelo de regresión lineal simple. 

Nótese que el pvalor ha venido acompañado de los tres asteriscos o estrellas. Ello indica que el grado de significancia es muy alto. 

## Paso 4: Identificando los coeficientes y construyendo la ecuación

Para ello, debemos ver nuevamente la tabla de coeficiente, la línea que corresponde a nuestra variable explicativa. En esta tenemos que prestar atención al número que figura en la columna *Estimate*.

No obstante, siempre sugiero solicitar el siguiente código para así evitar errores en la lectura del coeficiente:

    modelo1$coefficients

    ##     (Intercept) salario_inicial 
    ##      1928.20576         1.90945

Con este código le hemos dicho al programa que nos muestre los coeficientes del modelo 1. Por ello, al ser una regresión lineal simple, tenemos dos números: el intercepto y el coeficiente del salario inicial. 

Vemos que el coeficiente del salario inicial es 1.90945, por ello, podemos ver que la relación que existe entre salario inicial y salario actual es directa (al ser positivo el coeficiente).

Finalmente, para construir la ecuación utilizamos los coeficientes que hemos obtenido de la siguiente manera:

salario_actual = 1928.20576 + (1.90945*salario_inicial)

Con esta ecuación del *modelo1*, dado un valor de salario_inicial, nosotros podemos calcular el salario actual de un trabajador. 
