---
title: Predecir con regresión lineal múltiple
linktitle: Regresión lineal múltiple
toc: true
type: docs
date: "2019-05-05T00:00:00+01:00"
draft: false
menu:
  example:
    parent: 7. Modelamiento
    weight: 2

# Prev/next pager order (if `docs_section_pager` enabled in `params.toml`)
weight: 3
---

Te sugiero ver el siguiente tutorial para realizar un modelo de regresión lineal múltiple.

<iframe width="560" height="315" src="https://www.youtube.com/embed/XtDQD25Ejkc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# PASOS PREVIOS:

## Solicitamos nuestra base de datos desde la nube

    library(rio)
    base_trabajadores="https://github.com/DataPolitica/salidas/raw/master/Data/trabajadores.sav"
    trabajadores=import(base_trabajadores)
    attach(trabajadores)

    names(trabajadores)

    ##  [1] "id"              "sexo"            "fechnac"         "educ"           
    ##  [5] "catlab"          "salario_actual"  "salario_inicial" "antiguedad"     
    ##  [9] "experiencia"     "minoría"         "directivo"

## Solicitamos un modelo de regresión múltiple

Calculamos un modelo de regresión múltiple en el cual tenemos a *salario_actual* como dependiente y contamos con tres independiente o explicativas: el salario inicial del trabajador(*salario_inicial*), los años de educación del trabajador (*educ*) y los años de antiguedad en el cargo (*antiguedad*)

    modelo2=lm(salario_actual~salario_inicial + educ + antiguedad, data=trabajadores)

Luego, solicitamos el resultado utilizando la función `summary`:

    summary(modelo2)

    ## 
    ## Call:
    ## lm(formula = salario_actual ~ salario_inicial + educ + antiguedad, 
    ##     data = trabajadores)
    ## 
    ## Residuals:
    ##    Min     1Q Median     3Q    Max 
    ## -30325  -4231   -658   2924  46707 
    ## 
    ## Coefficients:
    ##                   Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)     -1.999e+04  3.237e+03  -6.175 1.43e-09 ***
    ## salario_inicial  1.689e+00  5.783e-02  29.209  < 2e-16 ***
    ## educ             9.661e+02  1.579e+02   6.118 2.00e-09 ***
    ## antiguedad       1.557e+02  3.506e+01   4.442 1.11e-05 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 7646 on 470 degrees of freedom
    ## Multiple R-squared:  0.8008, Adjusted R-squared:  0.7995 
    ## F-statistic: 629.7 on 3 and 470 DF,  p-value: < 2.2e-16

Una vez tengamos nuestro resultado seguimos nuevamente los pasos de nuestro flujograma:

## Paso 1: Comprobar si nuestro modelo es válido

Vemos la tabla ANOVA, vale decir, las últimas líneas de nuestro output del *modelo2*. 

| Hipótesis nula (H0)  | Hipótesis alterna (Ha) |
| ------------- | ------------- |
| El modelo no es válido  | El modelo es válido  |

Entonces leemos el p-valor. Como en este caso obtuvimos un p valor de <2.2e-16 entonces podemos ver que es menor a 0.05 (alpha), rechazamos la hipótesis nula y concluimos que **nuestro modelo es válido**.

## Paso 2: Capacidad explicativa del modelo

Para ello, debemos ver el valor del R2 ajustado. En este caso lo interpretamos de la siguiente manera:

![Image](/cursos/7-1-3.jpg)

En este caso, al tener un R2 ajustado de 0.7995 podemos concluir que nuestro modelo de regresión múltiple explica el 79.95% de la variabilidad de la dependiente (en este caso, salario actual).

## Paso 3: Verificar si las variables X´s aporta al modelo

Ahora que estamos considerando más de una variable, debemos verificar si efectivamente las tres variables explicativas aportan al modelo. 

Para ello, debemos visualizar nuevamente nuestra tabla de coeficientes y analizar la línea que corresponde a la variable de nuestro interés. 

| Hipótesis nula (H0)  | Hipótesis alterna (Ha) |
| ------------- | ------------- |
| La variable X no aporta al modelo  | La variable X aporta al modelo  |

En este caso, el pvalor de *salario_inicial* nos salió <2e-16*** ; el de *educ* salió 2.00e-09*** ; y el de *antiguedad* salió  1.11e-05***.

Por ello, podemos rechazar la hipótesis nula (la variable no aporta al modelo) en los tres casos y concluir que todas las variables aportan al modelo de regresión lineal múltiple. 
  
Nótese que todos los p-valor han venido acompañado de los tres asteriscos o estrellas. Ello indica que el grado de significancia es muy alto es las tres variables explicativas. 

## Paso 4: Identificando los coeficientes y construyendo la ecuación

Por último, solicitamos los coeficiente de nuestro modelo:

    modelo2$coefficients

    ##     (Intercept) salario_inicial            educ      antiguedad 
    ##    -19986.50217         1.68916       966.10701       155.70118

Con este código le hemos dicho al programa que nos muestre los coeficientes del modelo 2. En esta ocasión, al ser una regresión lineal múltiple, tenemos cuatro número: el intercepto y el coeficiente del salario_inicial, educ y antiguedad. Sobre los coeficiente podemos ver que:

Coeficiente del salario inicial es 1.90945. Es positivo, por ello, podemos ver que la relación es directa (mientras uno aumenta el otro aumenta).

Coeficiente de educ es 9.66.10701. Es positivo, la relación es directa.

Coeficiente de antiguedad es 155.70118. Es positivo, la relación es directa. 

Finalmente, para construir la ecuación utilizamos los coeficientes que hemos obtenido de la siguiente manera:

salario_actual = -19986.50217 + (1.68916*salario_inicial) + (966.10701*educ) + (155.70118*antiguedad)

Con esta ecuación del *modelo2*, dado un valor de salario_inicial, años de educación y años de antiguedad, nosotros podemos calcular el salario actual de un trabajador. 